name: ff-recovery
channels:
  - pytorch
  - omnia
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.13.0=pyhd8ed1ab_0
  - aiohttp=3.7.0=py38h1e0a361_0
  - async-timeout=3.0.1=py_1000
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - boost-cpp=1.70.0=ha2d47e9_1
  - brotlipy=0.7.0=py38h8df0ef7_1001
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.5.30=ha878542_0
  - cachetools=4.2.2=pyhd8ed1ab_0
  - certifi=2021.5.30=py38h578d9bd_0
  - cffi=1.14.6=py38h400218f_0
  - chardet=3.0.4=py38h924ce5b_1008
  - click=8.0.1=py38h578d9bd_0
  - cloudpickle=1.6.0=pyhd3eb1b0_0
  - cmake=3.14.0=h52cb24c_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - curl=7.78.0=h1ccaba5_0
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask-core=2021.8.1=pyhd3eb1b0_0
  - dataclasses=0.8=pyhc8e2a94_3
  - decorator=5.1.0=pyhd8ed1ab_0
  - double-conversion=3.1.5=he6710b0_1
  - eigen=3.3.7=hfd86e86_0
  - eigen3=3.3.7=0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.3.1=h3215721_1
  - flann=1.9.1=h44f99b7_1008
  - freetype=2.10.4=h5ab3b9f_0
  - fsspec=2021.7.0=pyhd3eb1b0_0
  - gl2ps=1.4.2=he06d7ca_0
  - glew=2.1.0=he1b5a44_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-auth=1.35.0=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - grpcio=1.33.2=py38heead2fc_2
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.6=nompi_h7c3c948_1111
  - icu=58.2=he6710b0_3
  - idna=2.10=pyh9f0ad1d_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py38h578d9bd_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipdb=0.13.9=pyhd8ed1ab_0
  - ipython=7.27.0=py38he5a9106_0
  - jedi=0.18.0=py38h578d9bd_2
  - jpeg=9d=h7f8727e_0
  - jsoncpp=1.8.4=hfd86e86_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libcurl=7.78.0=h0b77cf5_0
  - libedit=3.1.20210714=h7f8727e_0
  - libev=4.33=h7b6447c_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libglu=9.0.0=hf484d3e_1
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.2=h7f8727e_0
  - libnetcdf=4.7.4=nompi_h56d31a8_107
  - libnghttp2=1.41.0=hf8bcb03_2
  - libogg=1.3.5=h27cfd23_1
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.13.0.1=h8b12597_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtheora=1.1.1=h5ab3b9f_1
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.40.0=h7b6447c_0
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - locket=0.2.1=py38h06a4308_1
  - loguru=0.5.3=py38h578d9bd_2
  - lz4-c=1.9.2=heb0550a_3
  - markdown=3.3.4=pyhd8ed1ab_0
  - matplotlib-base=3.3.4=py38h62a2d02_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.2=py38h51133e4_0
  - multidict=4.7.5=py38h1e0a361_2
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.6.2=pyhd3eb1b0_0
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.20.3=py38hf144106_0
  - numpy-base=1.20.3=py38h74d4b33_0
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.1=h8b12597_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1l=h7f8727e_0
  - packaging=21.0=pyhd3eb1b0_0
  - parso=0.8.2=pyhd8ed1ab_0
  - partd=1.2.0=pyhd3eb1b0_0
  - pcl=1.9.1=h39e01aa_1004
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.1=py38h2c7a002_0
  - pip=21.2.2=py38h06a4308_0
  - proj=7.1.1=h966b41f_3
  - prompt-toolkit=3.0.20=pyha770c72_0
  - protobuf=3.13.0.1=py38hadf7658_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pugixml=1.10=he1b5a44_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pybind11=2.6.1=py38h82cb98a_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.11=h12debd9_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.9.0=py3.8_cuda11.1_cudnn8.0.5_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywavelets=1.1.1=py38h7b6447c_2
  - pyyaml=5.4.1=py38h27cfd23_1
  - qhull=2019.1=hc9558a2_0
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rhash=1.4.1=h3c74f83_1
  - rsa=4.7.2=pyh44b312d_0
  - scikit-image=0.18.1=py38ha9443f7_0
  - scipy=1.7.1=py38h292c36d_2
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tbb=2020.3=hfd86e86_0
  - tbb-devel=2020.3=hfd86e86_0
  - tensorboard=2.4.1=pyhd8ed1ab_1
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tifffile=2020.10.1=py38hdd07704_2
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - torchvision=0.2.2=py_3
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.62.2=pyhd3eb1b0_1
  - traitlets=5.1.0=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - utfcpp=3.2.1=ha770c72_0
  - vtk=9.0.1=no_osmesa_py38h31de780_102
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - x264=1!152.20180806=h7b6447c_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h36c2ea0_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxt=1.2.0=h516909a_0
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.3=py38h25fe258_0
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - argon2-cffi==21.1.0
    - bleach==4.1.0
    - chamferdist==1.0.0
    - cycler==0.10.0
    - cython==0.29.24
    - debugpy==1.4.3
    - defusedxml==0.7.1
    - descartes==1.1.0
    - dominate==2.6.0
    - entrypoints==0.3
    - fire==0.4.0
    - flask==2.0.2
    - html4vision==0.4.3
    - ipykernel==6.4.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - itsdangerous==2.0.1
    - jinja2==3.0.1
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==7.0.3
    - jupyter-console==6.4.0
    - jupyter-core==4.8.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - kiwisolver==1.3.2
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - mistune==0.8.4
    - nbclient==0.5.4
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.4
    - nuscenes-devkit==1.1.8
    - opencv-python==4.5.3.56
    - pandocfilters==1.5.0
    - plyfile==0.7.4
    - prometheus-client==0.11.0
    - pybind11-global==2.6.1
    - pycocotools==2.0.2
    - pyquaternion==0.9.9
    - pyrsistent==0.18.0
    - pyzmq==22.3.0
    - qtconsole==5.1.1
    - qtpy==1.11.1
    - scikit-learn==0.24.2
    - send2trash==1.8.0
    - shapely==1.7.1
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.5.0
    - threadpoolctl==2.2.0
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
prefix: /home/tkhurana/anaconda3/envs/ff-recovery

